### ISSUE TITLE
Добавить InvokeWhile

### ISSUE THREAD

**Issue by sergey-cs** [ltd-profit/omega-package#189]
`Routine.InvokeWhile(otherRoutine, () => Debug.Log("Update routine")`
WaitWith - возвращает рутину которая ждет `otherRoutine` и вызывает, переданную вторым аргументом, функцию на каждом обновлении (MoveNext) рутины

**Comment by DavidNightinga1e** [comment]
Название ничего не говорит о том что функция будет вызываться на каждом обновлении `otherRoutine`

**Comment by DavidNightinga1e** [comment]
ExecuteAlong
